### ISSUE TITLE
NullPointerException while percolating query

### ISSUE THREAD

**Issue by pawel-madurski** [jprante/elasticsearch-functionscore-conditionalboost#2]
Jörg thanks for you hard work.
There is some issue with percolating functionscore-conditionalboost query. I've made some debugging and the issue is in `CondBoostFactorFunctionParser.java` in line 
`MappedFieldType mappedFieldType = searchContext.mapperService().fullName(entry.fieldName);`
The problem is that `SearchContext.current()` is null. 
Can you help solving this issue? I'm rookie with elastic and I really appreciate for help.
Thanks
Paweł

**Comment by jprante** [comment]
For reproducing the issue, can you show me how the percolation query looks like? I'm afraid scoring only works in non-percolated queries at server side, i.e. with a search context.

**Comment by pawel-madurski** [comment]
You can use query from yours example 

`PUT test/.percolator/1
{
   "query": {
      "function_score": {
         "query": {
            "term": {
               "content": "foo"
            }
         },
         "cond_boost": {
            "cond": [
               {
                  "product": "product_name_1",
                  "value": 2
               },
               {
                  "user": "user_name_1",
                  "value": 3
               }
            ],
            "value": 1,
            "factor": 1,
            "modifier": "NONE"
         }
      }
   }
}`

And here is an entry from log with full call stack 
`[2016-06-24 01:47:53,870][WARN ][rest.suppressed          ] /test/.percolator/1 Params: {index=test, id=1, type=.percolator}
RemoteTransportException[[Gabriel the Air-Walker][127.0.0.1:9301][indices:data/write/index[p]]]; nested: PercolatorException[failed to parse query [1]]; nested: NullPointerException;
Caused by: [test] PercolatorException[failed to parse query [1]]; nested: NullPointerException;
        at org.elasticsearch.index.percolator.PercolatorQueriesRegistry.parsePercolatorDocument(PercolatorQueriesRegistry.java:182)
        at org.elasticsearch.index.percolator.PercolatorQueriesRegistry$RealTimePercolatorOperationListener.preIndex(PercolatorQueriesRegistry.java:301)
        at org.elasticsearch.index.indexing.ShardIndexingService.preIndex(ShardIndexingService.java:146)
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:595)
        at org.elasticsearch.index.engine.Engine$Index.execute(Engine.java:836)
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:237)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:158)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:66)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.xbib.elasticsearch.index.query.functionscore.condboost.CondBoostFactorFunctionParser.parseCondArray(CondBoostFactorFunctionParser.java:104)
        at org.xbib.elasticsearch.index.query.functionscore.condboost.CondBoostFactorFunctionParser.parse(CondBoostFactorFunctionParser.java:62)
        at org.elasticsearch.index.query.functionscore.FunctionScoreQueryParser.parse(FunctionScoreQueryParser.java:140)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
        at org.elasticsearch.index.query.IndexQueryParserService.parseInnerQuery(IndexQueryParserService.java:261)
        at org.elasticsearch.index.percolator.PercolatorQueriesRegistry.parseQuery(PercolatorQueriesRegistry.java:208)
        at org.elasticsearch.index.percolator.PercolatorQueriesRegistry.parsePercolatorDocument(PercolatorQueriesRegistry.java:179)
        ... 17 more`

**Comment by jprante** [comment]
Thanks.

I think I found a fix, please try version 2.3.3.1 (just released).

**Comment by pawel-madurski** [comment]
Jörg. 
Yours fix is working fine. Thanks for yours hard work again.
I love opens source community :)
